version: '3'
volumes:
  node_modules:
services:
  nodejs:
    build:
      context: './node'
      dockerfile: 'Dockerfile'
    volumes:
      - './node:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - CORS_DEBUG=1
      - SERVER=https://testing.com/
    ports:
      - '9123:8080'