version: '3'
volumes:
  node_modules:
services:
  nodejs:
    build:
      context: './node'
      dockerfile: 'Dockerfile_prod'
    environment:
      - VIRTUAL_HOST=${NODE_DOMAIN}
      - VIRTUAL_PORT=${NODE_PORT}
      - LETSENCRYPT_HOST=${NODE_DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    expose:
      - 80
    networks:
      - proxy
networks:
  proxy: 
    external: true